=== giellalt/dict-nob-fkv/dtd/nobfkv.dtd
<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e src CDATA #REQUIRED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr NMTOKEN #IMPLIED >
<!ATTLIST l pos ( A | Adv | CC | CS | Det | Interj | N | Num | Po | Pr | Pron | V ) #IMPLIED >
<!ATTLIST l t_type ( Phrase ) #IMPLIED >
<!ATTLIST l type NMTOKEN #IMPLIED >

<!ELEMENT lg ( l ) >

<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT mg ( re?, tg, syng? ) >

<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xml:lang (nob) #IMPLIED>
<!ATTLIST r id (nobfkv) #IMPLIED>

<!ELEMENT syng ( syn+ ) >
<!ELEMENT syn ( #PCDATA ) >
<!ELEMENT xhtml:script ( #PCDATA ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t val ( TV|IV ) #IMPLIED >
<!ATTLIST t pos ( A | Abbr | Adv | CC | Clt | CS | Det | Interj | N | Num | Pcle | Po | Pr | Pron | Prop | Qu | suff | V) #IMPLIED >
<!ATTLIST t src NMTOKEN #IMPLIED >
<!ATTLIST t stem CDATA #IMPLIED >
<!ATTLIST t type CDATA #IMPLIED >
<!ATTLIST t t_type ( Phrase ) #IMPLIED >
<!ATTLIST t href CDATA #IMPLIED >

<!ELEMENT tg ( re?, t+, xg* ) >
<!ATTLIST tg re CDATA #IMPLIED >
<!ATTLIST tg xml:lang NMTOKEN #FIXED "fkv" >
<!ATTLIST tg dial (p|j|v|pv|jv|pj) #IMPLIED >

<!ELEMENT re  ( #PCDATA )>
<!ATTLIST re
fra_ref CDATA #IMPLIED
>

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-nob-fkv/src/f1_nobfkv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE r PUBLIC "-//XMLmind//DTD nobfkv//FI" "../script/nobfkv.dtd">
<?xml-stylesheet type="text/css" href="../script/nobfkv.css"?>
<r xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <lics xml:space="preserve">
      <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>
      <ref>Work by Terje Aronsen and Verena Schall at Kainun institutti, Giellatekno at UiT,
          Divvun at the Norwegian Saami Parliament,
          and members of the language communities. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>
      <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted.
     </sourcenote>
   </lics>
   <e>
      <l decl="f1" pos="N">badebuks</l>
      <mg>
         <tg>
            <t pos="N">uimahousut</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ballongbukse</l>
      <mg>
         <tg>
            <t pos="N">palonkihousut</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">barmhjertighet</l>
      <mg>
         <tg>
            <t pos="N">lauppeus</t>
            <stem>lauppeuđe-</stem>
            <stem>lauppeut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">bukse</l>
      <mg>
         <tg>
            <t pos="N">housut</t>
         </tg>
      </mg>
      <syng>
         <syn>prakut</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">båtstø</l>
      <mg>
         <tg>
            <t pos="N">valkama</t>
         </tg>
      </mg>
      <syng>
         <syn>venheensija</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">dønning</l>
      <mg>
         <tg>
            <t pos="N">siikatet</t>
            <stem>siikathee-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">fjellrype</l>
      <mg>
         <tg>
            <t pos="N">kieruna</t>
         </tg>
         <tg>
            <t pos="N">tuntuririekko</t>
            <stem>tunturirieko-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">forside</l>
      <mg>
         <tg>
            <t pos="N">etupuoli</t>
            <stem>etupuole-</stem>
            <stem>etupuol-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">gjedde</l>
      <mg>
         <tg>
            <t pos="N">hauki</t>
            <stem>haue-</stem>
            <stem>haukke-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">godhet</l>
      <mg>
         <tg>
            <t pos="N">hyvvyys</t>
            <stem>hyvvyyđe-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">harv</l>
      <mg>
         <tg>
            <t pos="N">karhii</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">hytte</l>
      <mg>
         <tg>
            <t pos="N">mökki</t>
            <stem>möki-</stem>
         </tg>
         <tg>
            <t pos="N">hyttä</t>
            <stem>hytä-</stem>
         </tg>
      </mg>
      <syng>
         <syn>mökki</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">høyberging</l>
      <mg>
         <tg>
            <t pos="N">heinänkorju</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">innberging</l>
      <mg>
         <tg>
            <t pos="N">korju</t>
         </tg>
      </mg>
      <syng>
         <syn>heinänkorju</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">issørpe</l>
      <mg>
         <tg>
            <t pos="N">hyhmä</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">krigstid</l>
      <mg>
         <tg>
            <t pos="N">sođanaika</t>
            <stem>sođanaija-</stem>
            <stem>sođanaikka-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">kvern</l>
      <mg>
         <tg>
            <t pos="N">mylly</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">mattefille</l>
      <mg>
         <tg>
            <t pos="N">mattafilleri</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">merd</l>
      <mg>
         <tg>
            <t pos="N">merta</t>
            <stem>merra-</stem>
            <stem>mertta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">mørketid</l>
      <mg>
         <tg>
            <t pos="N">pimmeenaika</t>
            <stem>pimmeenaija-</stem>
            <stem>pimmeenaikka-</stem>
         </tg>
      </mg>
      <syng>
         <syn>kaamos</syn>
      </syng>
   </e>
   <e>
      <l decl="f1" pos="N">nise</l>
      <mg>
         <tg>
            <t pos="N">nissu</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">niste</l>
      <mg>
         <tg>
            <t pos="N">eväs</t>
            <stem>evhää-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">nonne</l>
      <mg>
         <tg>
            <t pos="N">nunna</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">renning</l>
      <mg>
         <tg>
            <t pos="N">luoma</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">rifle</l>
      <mg>
         <tg>
            <t pos="N">rikkopyssy</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">sannhet</l>
      <mg>
         <tg>
            <t pos="N">tottuus</t>
            <stem>tottuuđe-</stem>
            <stem>tottuut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">selvstendighet</l>
      <mg>
         <tg>
            <t pos="N">ittenäisyys</t>
            <stem>ittenäisyyđe-</stem>
            <stem>ittenäisyyt-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">sjørøye</l>
      <mg>
         <tg>
            <t pos="N">merirautu</t>
            <stem>merirauđu-</stem>
            <stem>merirauttu-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">skare</l>
      <mg>
         <tg>
            <t pos="N">roustet</t>
            <stem>rousthee-</stem>
         </tg>
         <tg>
            <t pos="N">kerstet</t>
            <stem>kersthee-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">skinnfell</l>
      <mg>
         <tg>
            <t pos="N">rouko</t>
            <stem>rouo-</stem>
            <stem>roukko-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">snelle</l>
      <mg>
         <tg>
            <t pos="N">kela</t>
            <stem>kella-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">stillhet</l>
      <mg>
         <tg>
            <t pos="N">hiljaisuus</t>
            <stem>hiljaisuuđe-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">stoppenål</l>
      <mg>
         <tg>
            <t pos="N">toppineula</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tavle</l>
      <mg>
         <tg>
            <t pos="N">taulu</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tilje</l>
      <mg>
         <tg>
            <t pos="N">telju</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">timelønn</l>
      <mg>
         <tg>
            <t pos="N">tiimapalkka</t>
            <stem>tiimapalka-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">trekullgrop</l>
      <mg>
         <tg>
            <t pos="N">sysihauta</t>
            <stem>sysihauđa-</stem>
            <stem>sysihautta-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">trofasthet</l>
      <mg>
         <tg>
            <t pos="N">uskolisuus</t>
            <stem>uskolisuuđe-</stem>
            <stem>uskolisuut-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">tromme</l>
      <mg>
         <tg>
            <t pos="N">trumma</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ugle</l>
      <mg>
         <tg>
            <t pos="N">ykla</t>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">veiledning</l>
      <mg>
         <tg>
            <t pos="N">opastus</t>
            <stem>opastukse-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">vindstille</l>
      <mg>
         <tg>
            <t pos="N">tyven</t>
            <stem>tyvene-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">åre</l>
      <mg>
         <tg>
            <t pos="N">airo</t>
            <stem>airro-</stem>
         </tg>
      </mg>
   </e>
   <e>
      <l decl="f1" pos="N">ødemark</l>
      <mg>
         <tg>
            <t pos="N">korpi</t>
            <stem>korve-</stem>
            <stem>korppe-</stem>
         </tg>
      </mg>
   </e>
   <xhtml:script type="text/javascript" src="../../scripts/gt_dictionary.js"/>
</r>
